version: '3.1'

services:

  mongo:
    container_name: bootcamp_mongodb
    image: mongo:4.4
    restart: always
    env_file:
      - .env
    ports:
      - "21017:21017"
    volumes:
      - ~/mongo:/data/db
    networks:
      - node-mongo-network

  mongo-express:
    container_name: bootcamp_mongo_express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
            - .env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_INITDB_ROOT_USERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_INITDB_ROOT_PASSWORD
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: 'mongo'    
    networks:
      - node-mongo-network
  
  mongo-seed:
    container_name: bootcamp_mongo_seed
    env_file:
        - .env
    build:
        context: .
        dockerfile: Dockerfile
        args:
            - DATABASE_URI=$DATABASE_URI
            - USERNAME=$MONGO_INITDB_ROOT_USERNAME
            - PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
    depends_on:
        - mongo
    networks:
        - node-mongo-network
networks:
  node-mongo-network:
    driver: bridge
