version: '3'
services:
  backend:
    container_name: python_app
    build: 
      context: ./myapp
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 5000:5000
    env_file:
            - .env
    environment:
      POSTGRES_DB: $PG_INITDB_APP_DATABASE
      POSTGRES_USER: $PG_INITDB_LOW_USERNAME
      POSTGRES_PASSWORD: $PG_INITDB_LOW_PASSWORD
      POSTGRES_HOST: postgress_db
      POSTGRES_PORT: 5432
    networks:
      - python_app-docker-network   

  db:
    container_name: postgress_db
    build: 
      context: ./postgres
      dockerfile: Dockerfile
    restart: always
    env_file:
            - .env
    environment:
      POSTGRES_DB: $PG_INITDB_DATABASE
      POSTGRES_USER: $PG_INITDB_ROOT_USERNAME
      POSTGRES_PASSWORD: $PG_INITDB_ROOT_PASSWORD
      POSTGRES_PASSWORD_APP: $PG_INITDB_LOW_PASSWORD
      POSTGRES_USER_APP: $PG_INITDB_LOW_USERNAME
      POSTGRES_DB_APP: $PG_INITDB_APP_DATABASE
    ports:
    - "5432:5432"
    networks:
      - python_app-docker-network   

networks:
  python_app-docker-network:
    driver: bridge